![MLA Logo](https://drive.corp.amazon.com/view/mrruckma@/MLA_headerv2.png?download=true)

## Numpy Tutorial:
Numpy main object is homogenous multi-dimensional array with elements of the same data type. Dimensions are called axes. Numpy’s array class is called ndarray. Some important attributes of ndarray:
* ndarray.ndim: the number of axes (dimensions) of the array.
* ndarray.shape: the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). 
* ndarray.size: the total number of elements of the array. This is equal to the product of the elements of shape.
* ndarray.dtype: An object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.


Creating a numpy array and reading some attributes. 

In [2]:
import numpy as np

a = np.array([2, 3, 5])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[2 3 5]
1
(3,)
3
int64


We can use “reshape” method to change the shape of our array. 

In [3]:
b = np.array([4, 5, 6, 12, 5.1, 42.4, 11, 8])
print(b)
print(b.reshape(2, 4))

[ 4.   5.   6.  12.   5.1 42.4 11.   8. ]
[[ 4.   5.   6.  12. ]
 [ 5.1 42.4 11.   8. ]]


Multi-dimensional arrays of ones or zeros can be created. 

In [4]:
np.zeros((4, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

Multi-dimensional arrays of specified number. 

In [6]:
np.full((3, 4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

When different type items are provided in the input list. They are cast to a common type. 

In [7]:
c = np.array([4, 5, 6, 5.1, 42.4, False, 8])
print(c)
c = np.array([4, 5, 6, 5.1, 42.4, False, "strhere"])
print(c)

[ 4.   5.   6.   5.1 42.4  0.   8. ]
['4' '5' '6' '5.1' '42.4' 'False' 'strhere']


Desired type of the array can be set when initializing the array.

In [8]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

Create array with numbers from a sequence.

In [9]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

We can create random numbers with Numpy’s “random” function.

Creating uniformly distributed numbers between 0-1.

In [10]:
np.random.random((3, 3))

array([[0.21752053, 0.64340764, 0.35782602],
       [0.98792987, 0.47398423, 0.85559086],
       [0.119916  , 0.57101973, 0.34413296]])

Creating normally distributed numbers with mean 0 and standard deviation 1.

In [11]:
np.random.normal(0, 1, (3, 3))

array([[ 0.1232211 ,  0.23592748, -1.89103561],
       [ 0.95681008,  0.5946605 , -0.55769189],
       [-1.43276176,  0.59709185, -0.34596621]])

Creating random integers between 0-5.

In [12]:
np.random.randint(0, 5, (4, 3))

array([[3, 1, 0],
       [1, 1, 2],
       [2, 2, 4],
       [4, 3, 2]])

We can create multi-dimensional arrays. 

In [13]:
a = np.arange(4)                         # 1d array
print(a)
b = np.arange(12).reshape(4,3)           # 2d array
print(b)
c = np.arange(24).reshape(2,3,4)         # 3d array
print(c)

[0 1 2 3]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


__Basic Operations:__ Arithmetic operations are applied element-wise. A new array with new values are created. 

In [14]:
a = np.array([4, 3, 12, 1])
b = np.array([5, 1, 4, 7])
print(a + b)
print(a * b)
print(a / b)

[ 9  4 16  8]
[20  3 48  7]
[0.8        3.         3.         0.14285714]


Element-wise multiplication is perfomed using “*” operator.

In [15]:
A = np.array( [ [5, 3], [2, 4] ] )
B = np.array( [ [2, 4], [6, 1] ])
A*B

array([[10, 12],
       [12,  4]])

Matrix product is performed using “dot” function operator (using the same A and B above). 

In [16]:
A.dot(B)

array([[28, 23],
       [28, 12]])

We can calculate simple statistics in arrays. 

In [17]:
a = np.array([2, 3, 4, 5, 12, 1])
print(a.sum())
print(a.min())
print(a.max())
print(a.std())


27
1
12
3.593976442141304


Numpy arrays can be sliced using the position indexes.

In [18]:
a = np.array([14, 15, 16, 17, 18, 19])
print(a[:2])
print(a[3:5])
print(a[3:])

[14 15]
[17 18]
[17 18 19]
