![MLA Logo](https://drive.corp.amazon.com/view/mrruckma@/MLA_headerv2.png?download=true)

## Pandas Tutorial:
pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language.

One fundamental difference between pandas and NumPy: NumPy arrays have one dtype for the entire array, while pandas DataFrames have one dtype per column


Import numpy and pandas 

In [1]:
import numpy as np
import pandas as pd

Create a pandas series

In [4]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


Create a pandas DataFrame from a NumPy array. We will add an index (in this case dates) as well as headings for the columns. This is a very common format for representing feature data in ML

In [13]:
dates = pd.date_range('20200101', periods=6)
print(dates)

pretend_data = np.random.randn(6, 4)
df = pd.DataFrame(pretend_data, index=dates, columns=['FeatureA', 'FeatureB', 'FeatureC', 'FeatureD'])
print(df)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06'],
              dtype='datetime64[ns]', freq='D')
            FeatureA  FeatureB  FeatureC  FeatureD
2020-01-01 -0.001860 -0.711122  0.048550 -1.072249
2020-01-02  0.023092  0.934692 -1.513385 -0.689602
2020-01-03  0.500320  2.443852  1.321200  0.813518
2020-01-04 -0.632864 -2.350005 -1.712395 -0.592897
2020-01-05  0.695928 -1.280266 -0.020780 -0.288791
2020-01-06  0.061051 -0.372759 -0.289839  0.162584


Creating a DataFrame by passing a dict of objects that can be converted to series-like 

In [15]:
df2 = pd.DataFrame({'A': 1.,
                    'B': pd.Timestamp('20130102'),
                    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D': np.array([3] * 4, dtype='int32'),
                    'E': pd.Categorical(["test", "train", "test", "train"]),
                    'F': 'foo'})
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo


What are the different type items in the DataFrame?

In [17]:
print(df2.dtypes)

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object


### Viewing DataFrames

View the top and bottom rows (note default number of rows shown by head and tail is 5)

In [21]:
df.head()
df2.tail(3)

A          B    C  D      E    F
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

Display the index and the columns separately

In [24]:
print(df.index)
print(df2.columns)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')


Convert from pandas DataFrame to NumPy array. <br>
Note1: This will cause pandas to find a NumPy dtype that is valid for all dtypes in the DataFrame <br>
Note2: Converstion to numpy will lose the index column as well as column labels

df is a DataFrame consisting entirely of elements of type float, so the resultant numpy array will preserve this type

In [40]:
a=df.to_numpy()
print(a)
a.dtype

[[-1.86041598e-03 -7.11122152e-01  4.85502983e-02 -1.07224930e+00]
 [ 2.30922578e-02  9.34691528e-01 -1.51338486e+00 -6.89602344e-01]
 [ 5.00319640e-01  2.44385200e+00  1.32119993e+00  8.13518029e-01]
 [-6.32864292e-01 -2.35000489e+00 -1.71239475e+00 -5.92897197e-01]
 [ 6.95927929e-01 -1.28026590e+00 -2.07804130e-02 -2.88790909e-01]
 [ 6.10510288e-02 -3.72758674e-01 -2.89839048e-01  1.62584127e-01]]


dtype('float64')

df2 is a DataFrame consisting multiple datatypes, so the resultant numpy array will consist of elements that have been cast to Python objects

In [43]:
b=df2.to_numpy()
print(b)
print(b.dtype)

[[1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'test' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'train' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'test' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'train' 'foo']]
object


Generate quick statistical summary of your numerical column data using describe()

In [51]:
df.describe()

FeatureA  FeatureB  FeatureC  FeatureD
count  6.000000  6.000000  6.000000  6.000000
mean   0.107611 -0.222601 -0.361108 -0.277906
std    0.462587  1.694403  1.120054  0.676025
min   -0.632864 -2.350005 -1.712395 -1.072249
25%    0.004378 -1.137980 -1.207498 -0.665426
50%    0.042072 -0.541940 -0.155310 -0.440844
75%    0.390502  0.607829  0.031218  0.049740
max    0.695928  2.443852  1.321200  0.813518

In [50]:
df2.describe()

A    C    D
count  4.0  4.0  4.0
mean   1.0  1.0  3.0
std    0.0  0.0  0.0
min    1.0  1.0  3.0
25%    1.0  1.0  3.0
50%    1.0  1.0  3.0
75%    1.0  1.0  3.0
max    1.0  1.0  3.0

Transpose

In [52]:
df.T

2020-01-01  2020-01-02  2020-01-03  2020-01-04  2020-01-05  \
FeatureA   -0.001860    0.023092    0.500320   -0.632864    0.695928   
FeatureB   -0.711122    0.934692    2.443852   -2.350005   -1.280266   
FeatureC    0.048550   -1.513385    1.321200   -1.712395   -0.020780   
FeatureD   -1.072249   -0.689602    0.813518   -0.592897   -0.288791   

          2020-01-06  
FeatureA    0.061051  
FeatureB   -0.372759  
FeatureC   -0.289839  
FeatureD    0.162584

Sorting by an axis: <br>
Note: In this case axis 0 is our rows (dates) and axis 1 is our columns (feature labels) <br>
Experiment with differenct axis and True/False for ascending

In [57]:
df.sort_index(axis=1, ascending=False)

FeatureD  FeatureC  FeatureB  FeatureA
2020-01-01 -1.072249  0.048550 -0.711122 -0.001860
2020-01-02 -0.689602 -1.513385  0.934692  0.023092
2020-01-03  0.813518  1.321200  2.443852  0.500320
2020-01-04 -0.592897 -1.712395 -2.350005 -0.632864
2020-01-05 -0.288791 -0.020780 -1.280266  0.695928
2020-01-06  0.162584 -0.289839 -0.372759  0.061051

Sort by values in a particular columns

In [59]:
df.sort_values(by='FeatureB', ascending=False)

FeatureA  FeatureB  FeatureC  FeatureD
2020-01-03  0.500320  2.443852  1.321200  0.813518
2020-01-02  0.023092  0.934692 -1.513385 -0.689602
2020-01-06  0.061051 -0.372759 -0.289839  0.162584
2020-01-01 -0.001860 -0.711122  0.048550 -1.072249
2020-01-05  0.695928 -1.280266 -0.020780 -0.288791
2020-01-04 -0.632864 -2.350005 -1.712395 -0.592897

### Selection

Select a single column

In [60]:
df['FeatureA']

2020-01-01   -0.001860
2020-01-02    0.023092
2020-01-03    0.500320
2020-01-04   -0.632864
2020-01-05    0.695928
2020-01-06    0.061051
Freq: D, Name: FeatureA, dtype: float64

Select rows

In [61]:
df[0:3]

FeatureA  FeatureB  FeatureC  FeatureD
2020-01-01 -0.001860 -0.711122  0.048550 -1.072249
2020-01-02  0.023092  0.934692 -1.513385 -0.689602
2020-01-03  0.500320  2.443852  1.321200  0.813518

Numpy arrays can be sliced using the position indexes.

In [62]:
df['2020-01-02':'2020-01-04']

FeatureA  FeatureB  FeatureC  FeatureD
2020-01-02  0.023092  0.934692 -1.513385 -0.689602
2020-01-03  0.500320  2.443852  1.321200  0.813518
2020-01-04 -0.632864 -2.350005 -1.712395 -0.592897